name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-extension:
    name: Build extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '18.12.1'
        run: |-
          npm install
          npm run build
          zip -r extension-${{ github.event.pull_request.head.sha }}.zip dist

      - name: Archive extension artifact
        uses: actions/upload-artifact@v2
        with:
          name: extension-${{ github.sha }}
          path: extension-${{ github.event.pull_request.head.sha }}.zip