name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '18.12.1'

      - name: Build
        run: |-
          npm install
          npm run build
          zip -r extension-${{ github.sha }}.zip dist

      - name: Archive extension artifact
        uses: actions/upload-artifact@v2
        with:
          name: extension-${{ github.sha }}
          path: extension-${{ github.sha }}.zip

      - name: Test
          npm run test
