name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-extension:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '18.12.1'
        run: |-
          npm install
          npm run test
